server:
  port: 2050

spring:
  application:
    name: CloudConfigServer
  cloud:
    config:
      server:
        git:
          #To configure local git repository
          uri: file:///D:/Workspace/spring-cloud-config-refresh-poc/spring-cloud-config-refresh-poc-config-repo
          #To configure remote git repository
          #uri: https://github.com/anilkumarb1248/spring-cloud-config-refresh-poc-config-repo
    bus:
      enabled: true
  kafka:
    bootstrap-servers: http://localhost:9092
          
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, refresh, bus-refresh
