server:
  port: 2053

message: Welcome to Admin Tool from local properties file
feature-flag: false

spring:
  application:
    name: AdminTool
  config:
    import: optional:configserver:http://localhost:2050

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, refresh, bus-refresh, beans, env
