server:
  port: 2053

message: Welcome to Admin Tool Service from local properties file
feature-flag: false

spring:
  application:
    name: Admin-Service
  config:
    import: optional:configserver:http://localhost:2050
  cloud:
    bus:
      refresh:
        enabled: true
      env:
        enabled: true
    stream:
      kafka:
        binder:
          autoAddPartitions: true
  kafka:
    bootstrap-servers: http://localhost:9092
    
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, refresh, bus-refresh
        
endpoints: 
  spring: 
    cloud: 
      bus: 
        refresh: 
          enabled: true
        env:
          enabled: true

        
#spring.cloud.bus.refresh.enabled=true
#spring.cloud.bus.env.enabled=true
#endpoints.spring.cloud.bus.refresh.enabled=true
#endpoints.spring.cloud.bus.env.enabled=true
#spring.cloud.stream.kafka.binder.autoAddPartitions=true
#spring.kafka.bootstrap-servers=http://localhost:9092

